TYPE: PoseHighResolutionNet
NAME: pose_hrnet_w48_384x288

# model-wide settings
FINAL_CONV_KERNEL: 1
PRETRAINED_LAYERS: ["*"]

# --- HRNet expects these as TOP-LEVEL ---
STAGE2:
  NUM_MODULES: 1
  NUM_BRANCHES: 2
  BLOCK: BASIC
  NUM_BLOCKS: [4, 4]
  NUM_CHANNELS: [48, 96]
  FUSE_METHOD: SUM

STAGE3:
  NUM_MODULES: 4
  NUM_BRANCHES: 3
  BLOCK: BASIC
  NUM_BLOCKS: [4, 4, 4]
  NUM_CHANNELS: [48, 96, 192]
  FUSE_METHOD: SUM

STAGE4:
  NUM_MODULES: 3
  NUM_BRANCHES: 4
  BLOCK: BASIC
  NUM_BLOCKS: [4, 4, 4, 4]
  NUM_CHANNELS: [48, 96, 192, 384]
  FUSE_METHOD: SUM

# --- THIS block is required in your build ---
PRESET:
  NUM_JOINTS: 17            # 26 if using Halpe-26
  IMAGE_SIZE: [384, 288]
  HEATMAP_SIZE: [96, 72]
  SIGMA: 2

