TYPE: PoseHighResolutionNet
NAME: pose_hrnet_w32_384x288

# global opts
FINAL_CONV_KERNEL: 1
PRETRAINED_LAYERS: ["*"]

# --- STAGES MUST BE TOP-LEVEL FOR YOUR REPO ---
STAGE2:
  NUM_MODULES: 1
  NUM_BRANCHES: 2
  BLOCK: BASIC
  NUM_BLOCKS: [4, 4]
  NUM_CHANNELS: [32, 64]
  FUSE_METHOD: SUM

STAGE3:
  NUM_MODULES: 4
  NUM_BRANCHES: 3
  BLOCK: BASIC
  NUM_BLOCKS: [4, 4, 4]
  NUM_CHANNELS: [32, 64, 128]
  FUSE_METHOD: SUM

STAGE4:
  NUM_MODULES: 3
  NUM_BRANCHES: 4
  BLOCK: BASIC
  NUM_BLOCKS: [4, 4, 4, 4]
  NUM_CHANNELS: [32, 64, 128, 256]
  FUSE_METHOD: SUM

# --- REQUIRED BY alphapose/models/hrnet.py ---
PRESET:
  NUM_JOINTS: 17         # set 26 if using Halpe-26
  IMAGE_SIZE: [384, 288] # (W, H)
  HEATMAP_SIZE: [96, 72] # (W/4, H/4)
  SIGMA: 2
